### ISSUE TITLE
iOS 14 break CubeLayout

### ISSUE THREAD

**Issue by 97mik** [KelvinJin/AnimatedCollectionViewLayout#60]
Xcode 12, iOS 14.
iOS 12 - everything is fine
![Screen Recording 2020-09-17 at 6 28 11 PM](https://user-images.githubusercontent.com/27870834/93492819-ec289980-f913-11ea-9943-9595e1939e28.gif)

**Comment by lautarodelosheros** [comment]
Same here, it's breaking with the new update. Any updates on this, or any workaround?

**Comment by KelvinJin** [comment]
Hey guys, thanks for reporting. I'll have a look this weekend. Should be an easy fix!

**Comment by eaceto** [comment]
Hi Kelvin. If you need help testing this, or figuring out why, let us now so we can help you. I could find right now why this happens!
Also, just to confirm. It seems to work okey on iOS 12, the problem seems to be Xcode, not iOS.
thanks!

**Comment by KelvinJin** [comment]
@97mik @lautarodelosheros @eaceto Hey guys, version 1.1.0 is now released. It should fix this issue on iOS 14. Let me know if it works for you guys!

**Comment by 97mik** [comment]
@KelvinJin it works for me, thanks!

**Comment by eaceto** [comment]
It is still broken for me, building with Xcode 11.7 and running on iOS 13

**Comment by KelvinJin** [comment]
@eaceto Hey, I just tested the Example project with Xcode 11 and iOS 13 simulator. The cube animator is working correctly for me. My understanding of this issue is it's only introduced by iOS 14 UIKit changes. Previous iOS versions should be fine. Do you want to create a new issue regarding your particular problem? Be aware that Cube animator changes the transform/anchorpoint of the cell's contentView so make sure you avoid changing these two properties yourself.

**Comment by KelvinJin** [comment]
@eaceto https://github.com/KelvinJin/AnimatedCollectionViewLayout/issues/61 Now I understand why I couldn't reproduce your issue. Have a look at the other issue ticket.

**Comment by eaceto** [comment]
I fixed it. Could I send a MR?
